[package]
name = "swc-svelte"
version = "0.1.0"
authors = ["Ottomated <otto@ottomated.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"

swc_ecma_ast = { version = "0.121.0", features = ["serde-impl"] }
swc_common = "0.40.0"
swc_ecma_parser = { version = "0.152.0", features = ["typescript"] }
serde_json = "1.0.128"
getrandom = { version = "0.2.15", features = ["js"] }
gloo-utils = { version = "0.2.0", features = ["serde"] }
swc_estree_compat = "0.215.0"
swc_node_comments = "0.27.0"
swc_estree_ast = "0.30.0"
js-sys = "0.3.70"

[dev-dependencies]
wasm-bindgen-test = "0.3.34"
