[package]
name = "oxc-svelte"
version = "0.1.0"
authors = ["Ottomated <otto@ottomated.net>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.84"
console_error_panic_hook = "0.1.7"
oxc_allocator = "0.30.5"
oxc_ast = { version = "0.30.5", features = ["serialize"] }
oxc_codegen = "0.30.5"
oxc_parser = "0.30.5"
oxc_semantic = "0.30.5"
oxc_span = "0.30.5"
oxc_transformer = "0.30.5"
serde_json = "1.0.128"
js-sys = "0.3.70"
gloo-utils = { version = "0.2.0", features = ["serde"] }

[patch.crates-io]
oxc_parser = { path = './target/patch/oxc_parser-0.30.5' }

[dev-dependencies]
wasm-bindgen-test = "0.3.34"

[build-dependencies]
anyhow = "1.0.89"
cargo = "0.82.0"
fs_extra = "1.3.0"
